config/routes.rb
KnowledgeBase::Application.routes.draw do
  resources :categorias

  resources :conhecimentos

  resources :autors

  match 'home/pesquisa' => "home#pesquisa"

  root :controller => "home", :action => "index"

end

app/models/autor.rb
class Autor < ActiveRecord::Base

	cattr_reader :per_page
	@@per_page = 10

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
	cattr_reader :per_page
	@@per_page = 10
end

app/models/conhecimento.rb
class Conhecimento < ActiveRecord::Base
	belongs_to :autor
	belongs_to :categoria

	cattr_reader :per_page
	@@per_page = 10
end

app/controllers/application.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time

  # See ActionController::RequestForgeryProtection for details
  # Uncomment the :secret if you're not using the cookie session store
  protect_from_forgery # :secret => 'e01b04e96232f7768c6375a08973ef8c'
  
  # See ActionController::Base for details 
  # Uncomment this to filter the contents of submitted sensitive data parameters
  # from your application log (in this case, all fields with names like "password"). 
  # filter_parameter_logging :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  # GET /autors
  # GET /autors.xml
  def index
    @autors = Autor.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @autors }
    end
  end

  # GET /autors/1
  # GET /autors/1.xml
  def show
    @autor = Autor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @autor }
    end
  end

  # GET /autors/new
  # GET /autors/new.xml
  def new
    @autor = Autor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @autor }
    end
  end

  # GET /autors/1/edit
  def edit
    @autor = Autor.find(params[:id])
  end

  # POST /autors
  # POST /autors.xml
  def create
    @autor = Autor.new(params[:autor])

    respond_to do |format|
      if @autor.save
        format.html { redirect_to(@autor, :notice => 'Autor was successfully created.') }
        format.xml  { render :xml => @autor, :status => :created, :location => @autor }
	format.js {render :layout=>false}
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @autor.errors, :status => :unprocessable_entity }
	format.js {render :layout=>false}
      end
    end
  end

  # PUT /autors/1
  # PUT /autors/1.xml
  def update
    @autor = Autor.find(params[:id])

    respond_to do |format|
      if @autor.update_attributes(params[:autor])
        format.html { redirect_to(@autor, :notice => 'Autor was successfully updated.') }
        format.xml  { head :ok }
	format.js { render :layout => false }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @autor.errors, :status => :unprocessable_entity }
	format.js { render :layout => false }
      end
    end
  end

  # DELETE /autors/1
  # DELETE /autors/1.xml
  def destroy
    @autor = Autor.find(params[:id])
    @autor.destroy

    respond_to do |format|
      format.html { redirect_to(autors_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/categorias_controller.rb
class CategoriasController < InheritedResources::Base
	def create
		@categoria = Categoria.new params[:categoria]

    respond_to do |format|
      if @categoria.save
      format.html { redirect_to(@categoria, :notice => 'Autor was successfully created.') }
      format.xml  { render :xml => @categoria, :status => :created, :location => @categoria }
      format.js {render :layout=>false}
       else
        format.html { render :action => "new" }
        format.xml  { render :xml => @categoria.errors, :status => :unprocessable_entity }
	format.js {render :layout=>false}
       end
      end
    end

  def update
    @categoria = Categoria.find(params[:id])

    respond_to do |format|
      if @categoria.update_attributes(params[:categoria])
        format.html { redirect_to(@autor, :notice => 'Categoria was successfully updated.') }
        format.xml  { head :ok }
	format.js { render :layout => false }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @autor.errors, :status => :unprocessable_entity }
	format.js { render :layout => false }
      end
    end
  end
end

app/controllers/conhecimentos_controller.rb
class ConhecimentosController < InheritedResources::Base
	actions :all, :except => ["destroy", "create", "update"]

	def destroy

		@conhecimento = Conhecimento.find(params[:id])
		@conhecimento.destroy
		@conhecimentos = Conhecimento.find(:all, :select => "id, titulo, autor_id")

		respond_to do |format|
	    		format.js {render :layout=>false}
		end

	end

	def create
		@conhecimento = Conhecimento.new(params[:conhecimento])
		@conhecimento.save
		
		respond_to do |format|
			format.js {render :layout=>false}
		end
	end

	def update
		@conhecimento = Conhecimento.find(params[:id])
		@conhecimento.update_attributes(params[:conhecimento])

		respond_to do |format|
			format.js {render :layout=> false}
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@conhecimentos = Conhecimento.paginate :page=>params[:pagina_conhecimentos], :order => "id DESC", :select => "id, titulo, autor_id, categoria_id"
	@autors = Autor.paginate :order => "id DESC", :page => params[:pagina_autores]
	@categorias = Categoria.paginate :order => "id DESC", :page => params[:pagina_categorias]
  end

  def pesquisa
	@autors = Autor.paginate :order => "id DESC", :page => params[:pagina_autores]

	@tp_pesquisa = params[:tp_pesquisa]
	@txt_pesquisa = params[:txt_pesquisa]

	case @tp_pesquisa
		when "co"
			@conhecimentos = Conhecimento.paginate_by_sql "select co.id, titulo, autor_id, categoria_id from conhecimentos co where co.titulo like '%#{@txt_pesquisa}%' OR co.texto like '%#{@txt_pesquisa}%'", :page => params[:pagina_conhecimentos], :order => "id DESC"
		when "c"
			@conhecimentos = Conhecimento.paginate_by_sql "select co.id, titulo, autor_id, categoria_id from conhecimentos co join categorias c on c.nome_categoria like '%#{@txt_pesquisa}%' and co.categoria_id = c.id", :page => params[:pagina_conhecimentos], :order => "id DESC" 

		when "a"
			@conhecimentos = Conhecimento.paginate_by_sql "select co.id, titulo, autor_id, categoria_id from conhecimentos co, autors a where (a.nome like '%#{@txt_pesquisa}%' AND co.autor_id = a.id)", :page => params[:pagina_conhecimentos], :order => "id DESC"
		else 
			@conhecimentos = Conhecimento.paginate_by_sql "select co.id, co.titulo, co.autor_id, co.categoria_id from conhecimentos co, categorias c, autors a where co.titulo like '%#{@txt_pesquisa}%' OR co.texto like '%#{@txt_pesquisa}%' OR (a.nome like '%#{@txt_pesquisa}%' AND co.autor_id = a.id) OR (c.nome_categoria like '%#{@txt_pesquisa}%' AND c.id = co.categoria_id) group by co.id", :page => params[:pagina_conhecimentos] 
	end

	render :action => "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/conhecimentos_helper.rb
module ConhecimentosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/autors/_form.html.erb
<%= simple_form_for(@autor, :remote => true) do |f| %>
	<label for="nome_autor" class="lbl_form">Nome do autor</label>
	<%= f.input :nome, :required => true, :label => false, :input_html => {:size=>"30", :id=>"txt_titulo", :maxlength=>"50"}%>

	<div id="div_btn_send"><%= f.button :submit, :value => "enviar" %></div>

<% end %>

<div id="dialog" title="Inserção de autor" style="display:none">
	<p><span class="ui-icon ui-icon-info" style="float:left; margin:0 7px 20px 0;"></span>Inserção feita com sucesso</p>
</div>

<div id="dialog_error" title="Inserção de autor" style="display:none">
	<p><span class="ui-icon ui-icon-info" style="float:left; margin:0 7px 20px 0;"></span>Problemas ao inserir autor</p>
</div>

app/views/autors/_index.html.erb
<div id="conteudo" class="ui-widget-content">
<h4><span class="ui-icon ui-icon-play"></span>autores cadastrados</h4>

<table>
  <tr>
    <th>Nome</th>
  </tr>

<% @autors.each do |autor| %>
  <tr>
    <td><%= link_to autor.nome, autor %></td>
    <td><%= link_to 'Editar', edit_autor_path(autor) %></td>
    <td><%= link_to 'Apagar', autor, :method => :delete, :remote => true, :id => "link_excluir_#{autor.id}", :class => "link_excluir" %></td>
  </tr>
<% end %>
</table>
</div>
<%= will_paginate @autors,:param_name => "pagina_autores", :previous_label => "anterior",:next_label => "próximo",:class => "ui-widget-header pagination" %>

app/views/autors/create.js.erb
<% if @autor.errors.any? %>
			$("#dialog_error").dialog({
				resizable:false,
				height:240,
				width:500,
				modal: true,
				buttons: {
					'fechar': function() { 
						window.location.href="/";
						$(this).dialog("close");
						
					}
				}
			})

<% else %>

			$("#dialog").dialog({
				resizable:false,
				height:240,
				width:500,
				modal: true,
				buttons: {
					'Ok': function() { 
						window.location.href="/";
						$(this).dialog("close");
						
					}
				}
			})
<% end %>

app/views/autors/edit.html.erb
<div id="conteudo" class="ui-widget-content ui-corner-bottom">
<h4><span class="ui-icon ui-icon-play"></span>Editando conhecimento</h4>
<%= render 'form' %>
</div>

app/views/autors/new.html.erb
<div id="conteudo" class="ui-widget-content ui-corner-bottom">
<h4><span class="ui-icon ui-icon-play"></span>Adicionar autor</h4>
<%= render 'form' %>
</div>

<div id="dialog" title="Inserção de autor" style="display:none">
	<p><span class="ui-icon ui-icon-info" style="float:left; margin:0 7px 20px 0;"></span>Inserção feita com sucesso</p>
</div>

<div id="dialog_error" title="Inserção de autor" style="display:none">
	<p><span class="ui-icon ui-icon-info" style="float:left; margin:0 7px 20px 0;"></span>Problemas ao inserir autor</p>
</div>

app/views/autors/show.html.erb
<div id="conteudo" class="ui-widget-content titulo_detalhes ui-corner-bottom">
<h4><span class="ui-icon ui-icon-play"></span>detalhes do autor</h4>

<span class="autor_detalhe_conhecimento"><%=@autor.nome%></span>
<br/>
</div>

app/views/autors/update.js.erb
<% if @autor.errors.any? %>
			$("#dialog_error").dialog({
				resizable:false,
				height:240,
				width:500,
				modal: true,
				buttons: {
					'fechar': function() { 
						window.location.href="/";
						$(this).dialog("close");
						
					}
				}
			})

<% else %>

			$("#dialog").dialog({
				resizable:false,
				height:240,
				width:500,
				modal: true,
				buttons: {
					'Ok': function() { 
						window.location.href="/";
						$(this).dialog("close");
						
					}
				}
			})
<% end %> 

app/views/categorias/_form.html.erb
<%= simple_form_for(@categoria, :remote => true) do |f| %>
	<label for="nome_categoria" class="lbl_form">Nome da categoria</label>
	<%= f.input :nome_categoria, :required => true, :label => false, :input_html => {:size=>"30", :id=>"txt_titulo", :maxlength=>"50"}%>

	<div id="div_btn_send"><%= f.button :submit, :value => "enviar" %></div>

<% end %>

<div id="dialog" title="Inserção de categoria" style="display:none">
	<p><span class="ui-icon ui-icon-info" style="float:left; margin:0 7px 20px 0;"></span>Inserção feita com sucesso</p>
</div>

<div id="dialog_error" title="Inserção de categoria" style="display:none">
	<p><span class="ui-icon ui-icon-info" style="float:left; margin:0 7px 20px 0;"></span>Problemas ao inserir conhecimento</p>
</div>

app/views/categorias/_index.html.erb
<div id="conteudo" class="ui-widget-content" style="border:1px solid black">
<h4><span class="ui-icon ui-icon-play"></span>categorias cadastradas</h4>
<table>
  <tr>
    <th>Nome categoria</th>
  </tr>

<% @categorias.each do |categoria| %>
  <tr>
    <td><%= link_to "#{categoria.nome_categoria}", categoria %></td>
    <td><%= link_to 'Editar', edit_categoria_path(categoria) %></td>
    <td><%= link_to 'Apagar', categoria,:method => :delete, :remote => true, :id=>"link_excluir_#{categoria.id}", :class=>"link_excluir"%></td>
  </tr>
<% end %>
</table>
</div>
<%= will_paginate @categorias,:param_name => "pagina_categorias", :previous_label => "anterior",:next_label => "próximo",:class => "ui-widget-header pagination" %>


<div id="div_rodape" class="ui-widget-header ui-corner-bottom" style="border:1px solid black;background-color:black;background-image:none"><br/></div>

app/views/categorias/create.js.erb
<% if @categoria.errors.any? %>
			$("#dialog_error").dialog({
				resizable:false,
				height:240,
				width:500,
				modal: true,
				buttons: {
					'fechar': function() { 
						window.location.href="/";
						$(this).dialog("close");
						
					}
				}
			})

<% else %>

			$("#dialog").dialog({
				resizable:false,
				height:240,
				width:500,
				modal: true,
				buttons: {
					'Ok': function() { 
						window.location.href="/";
						$(this).dialog("close");
						
					}
				}
			})
<% end %>

app/views/categorias/edit.html.erb
<div id="conteudo" class="ui-widget-content ui-corner-bottom">
<h4><span class="ui-icon ui-icon-play"></span>Editando categoria</h4>
<%= render 'form' %>
</div>

app/views/categorias/new.html.erb
<div id="conteudo" class="ui-widget-content ui-corner-bottom">
<h4><span class="ui-icon ui-icon-play"></span>Adicionar categoria</h4>
<%= render 'form' %>
</div>

<div id="dialog" title="Inserção de categoria" style="display:none">
	<p><span class="ui-icon ui-icon-info" style="float:left; margin:0 7px 20px 0;"></span>Inserção feita com sucesso</p>
</div>

<div id="dialog_error" title="Inserção de categoria" style="display:none">
	<p><span class="ui-icon ui-icon-info" style="float:left; margin:0 7px 20px 0;"></span>Problemas ao inserir categoria</p>
</div>

app/views/categorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome categoria:</b>
  <%= @categoria.nome_categoria %>
</p>


<%= link_to 'Edit', edit_categoria_path(@categoria) %> |
<%= link_to 'Back', categorias_path %>

app/views/categorias/update.js.erb
<% if @categoria.errors.any? %>
			$("#dialog_error").dialog({
				resizable:false,
				height:240,
				width:500,
				modal: true,
				buttons: {
					'fechar': function() { 
						window.location.href="/";
						$(this).dialog("close");
						
					}
				}
			})

<% else %>

			$("#dialog").dialog({
				resizable:false,
				height:240,
				width:500,
				modal: true,
				buttons: {
					'Ok': function() { 
						window.location.href="/";
						$(this).dialog("close");
						
					}
				}
			})
<% end %> 

app/views/conhecimentos/_form.html.erb
<%= simple_form_for(@conhecimento, :remote => true) do |f| %>
	<label for="txt_titulo" class="lbl_form">Título</label>
    	<%= f.input :titulo, :required => true, :label => false, :input_html => {:size=>"30", :id=>"txt_titulo", :maxlength=>"50"}%>

	<label for="select_autor" class="lbl_form">Autor</label>
	<%= f.association :autor, :label => false, :as => :select, :label_method => :nome, :input_html => {:id => "select_autor"} %>

	<label for="select_categoria" class="lbl_form">Categoria</label>
	<%= f.association :categoria, :label => false, :as => :select, :label_method => :nome_categoria, :input_html => {:id => "select_categoria"} %>
	<label for="txt_texto" class="lbl_form">Texto</label>
	<%= f.input :texto, :required => :true, :label => false, :input_html => {:id => "txt_texto", :rows=>"12", :cols=>"60"} %>

        <div id="div_btn_send"><%= f.button :submit, :remote=>true, :value=>"enviar", :id => "btn_send_conhecimento"%></div>
	
<% end %>

<div id="dialog" title="Inserção de autor" style="display:none">
	<p><span class="ui-icon ui-icon-info" style="float:left; margin:0 7px 20px 0;"></span>Inserção feita com sucesso</p>
</div>

<div id="dialog_error" title="Inserção de autor" style="display:none">
	<p><span class="ui-icon ui-icon-info" style="float:left; margin:0 7px 20px 0;"></span>Problemas ao inserir conhecimento</p>
</div>

app/views/conhecimentos/_index.html.erb
<div id="conteudo" class="ui-widget-content">
<h4><span class="ui-icon ui-icon-play"></span>conhecimentos cadastrados</h4>

<table>
  <tr>
    <th>Autor / Titulo</th>
    <th>Categoria</th>
  </tr>
<% @conhecimentos.each do |conhecimento| %>
  <tr>
    <td><%= link_to "#{conhecimento.autor.nome} / #{conhecimento.titulo}", conhecimento %></td>
    <td><%= link_to "#{conhecimento.categoria.nome_categoria}", conhecimento %></td>
    <td><%= link_to 'Editar', edit_conhecimento_path(conhecimento) %></td>
    <td><%= link_to 'Apagar', conhecimento,:method => :delete, :remote => true, :id=>"link_excluir_#{conhecimento.id}", :class=>"link_excluir"%></td>
  </tr>
<% end %>
</table>
</div>
<%= will_paginate @conhecimentos,:param_name => "pagina_conhecimentos", :previous_label => "anterior",:next_label => "próximo",:class => "ui-widget-header pagination" %>

<div id="dialog-confirm" title="Confirma essa exclusão?" style="display:none">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Esse dado será removido permanentemente</p>
</div>

app/views/conhecimentos/create.js.erb
<% if @conhecimento.errors.any? %>
			$("#dialog_error").dialog({
				resizable:false,
				height:240,
				width:500,
				modal: true,
				buttons: {
					'fechar': function() { 
						window.location.href="/";
						$(this).dialog("close");
						
					}
				}
			})

<% else %>

			$("#dialog").dialog({
				resizable:false,
				height:240,
				width:500,
				modal: true,
				buttons: {
					'Ok': function() { 
						window.location.href="/";
						$(this).dialog("close");
						
					}
				}
			})
<% end %>

app/views/conhecimentos/destroy.js.erb
//$('#conteudo').html("<%= escape_javascript render( :partial => "conhecimentos/index", :layout=> false ) %>")

app/views/conhecimentos/edit.html.erb
<div id="conteudo" class="ui-widget-content ui-corner-bottom">
<h4><span class="ui-icon ui-icon-play"></span>Editar conhecimento</h4>

<%= render 'form' %>

</div>

app/views/conhecimentos/index.html.erb
<div id="conteudo" class="ui-widget-content">
<h4> <span class="ui-icon ui-icon-play"></span>conhecimentos cadastrados</h4>

<table id="conhecimentos">
  <tr>
    <th>Autor</th>
    <th>Titulo</th>
    <th>Texto</th>
  </tr>

<% for conhecimento in @conhecimentos %>
  <tr>
    <td><%=h conhecimento.autor.nome %><%=h conhecimento.id %></td>
    <td><%=h conhecimento.titulo %></td>
    <td><%=h conhecimento.texto %></td>
    <td><%= link_to '<span class="ui-icon ui-icon-search"></span>mostrar', conhecimento %></td>
    <td><%= link_to '<span class="ui-icon ui-icon-wrench"></span>editar', edit_conhecimento_path(conhecimento) %></td>
    <td><%= link_to '<span class="ui-icon ui-icon-close"></span>apagar', "conhecimentos", :id=>"del_conhecimento_#{conhecimento.id}", :class=>"delete", :onclick => "window.href_deletar='/conhecimentos/#{conhecimento.id}'" %></td>

    <td><%= link_to '<span class="ui-icon ui-icon-close"></span>apagar', conhecimento, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />
</div>

<div id="confirma_exclusao" title="Excluir?">
</div>
<script type="text/javascript">
	$(document).ready(function()	{
		$("a.delete").click(function() {
			$("#confirma_exclusao").dialog('open');
			return false;
		})

		$("#confirma_exclusao").dialog({
			autoOpen:false,
			height:350,
			width:350,
			modal:true,
			buttons: {
				"Não": function() { $(this).dialog('close');return false; },
				"Sim":function() {
				$.post(window.href_deletar, {_method: "delete", authenticity_token: "<%= form_authenticity_token%>"}, function(data) {
	alert("fsdf");
});
			$("#confirma_exclusao").dialog('close');
				}
			}
		})
	})
</script>
<%= form_authenticity_token %>

app/views/conhecimentos/new.html.erb
<div id="conteudo" class="ui-widget-content ui-corner-bottom">
<h4><span class="ui-icon ui-icon-play"></span>Adicionar conhecimento</h4>

<%= render 'form' %>

</div>

app/views/conhecimentos/show.html.erb
<div id="conteudo" class="ui-widget-content titulo_detalhes ui-corner-bottom">
<h4><span class="ui-icon ui-icon-play"></span>detalhes do conhecimento</h4>
<span class="titulo_detalhes"><%=@conhecimento.titulo%></span>
<span class="autor_detalhe_conhecimento">(<%=@conhecimento.autor.nome%>)</span>
<br/>


<p class="texto_detalhes"><%=@conhecimento.texto%></p>

app/views/conhecimentos/update.js.erb
<% if @conhecimento.errors.any? %>
			$("#dialog_error").dialog({
				resizable:false,
				height:240,
				width:500,
				modal: true,
				buttons: {
					'fechar': function() { 
						window.location.href="/";
						$(this).dialog("close");
						
					}
				}
			})

<% else %>

			$("#dialog").dialog({
				resizable:false,
				height:240,
				width:500,
				modal: true,
				buttons: {
					'Ok': function() { 
						window.location.href="/";
						$(this).dialog("close");
						
					}
				}
			})
<% end %> 

app/views/home/index.html.erb
<%= render :partial=>"conhecimentos/index"%>
<%= render :partial=>"autors/index"%>
<%= render :partial=>"categorias/index"%>

app/views/home/pesquisa.html.erb
sfd

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Base de conhecimento</title>
  <%= csrf_meta_tag %>
  <%= javascript_include_tag "/jquery_ui/js/jquery-1.4.2.min.js", "/jquery_ui/js/jquery-ui-1.8.4.custom.min.js", "rails.js", "application.js" %>
  <%= stylesheet_link_tag "/jquery_ui/css/production/jquery-ui-1.8.4.custom.css", "/jquery_ui/css/production/header.ui.css", "/jquery_ui/css/production/content.ui.css", "estilo.css"%>

</head>
<body bgcolor="#FFF">
<div class="ui-widget">
	<div id="menu_header" class="ui-widget-content ui-state-default ui-corner-top">
		<span id="hd_go_home"><%=link_to "home", "/" %></span>
		<span id="hd_add_new_conhecimento"><%=link_to "+ conhecimento", new_conhecimento_path %></span>
		<span id="hd_add_new_autor"><%=link_to "+ autor", new_autor_path %></span>
		<span id="hd_add_new_autor"><%=link_to "+ categoria", new_categoria_path %></span>
		<span id="hd_pesquisa">
		<form method="post" action="/home/pesquisa" id="frm_pesquisa" style="display:inline">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
			pesquisar:
			<input type="text" name="txt_pesquisa" id="txt_pesquisa" class="ui-corner-all" value="<%=params[:txt_pesquisa]%>"/>
			<select name="tp_pesquisa" id="tp_pesquisa" class="ui-corner-all">
				<option value="">tudo</option>
				<option value="c">categorias</option>
				<option value="a">autores</option>
				<option value="co">conhecimentos</option>
			</select>
			
		</span>
		<span id="spn_btn_pesquisa" class="ui-icon ui-icon-play" style="display:inline-block;cursor:pointer" onclick="$('#frm_pesquisa').submit()">
		</form>
		</span>
	</div>
</div>
<%= yield %>

</body>
</html>